### ISSUE TITLE
npm run error ELIFECYCLE

### ISSUE THREAD

**Issue by fmadelino** [louisbros/pack-lambda#1]
Hello Louis,

Was trying out your package in windows and it was giving the following error:

Error: spawn npm ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

The problem on this is that the npm package was only considering Node on Linux flavor platforms...

Can you please update your package and replace:
const pack = spawn('npm', ['pack']);

with

const pack = spawn(/^win/.test(process.platform) ? 'npm.cmd' : 'npm', ['pack']);

Thanks

Regards
Filipe Madelino

**Comment by joelderrickclad** [comment]
I added **"C:\Windows\System32"** path to environment variable list and restarted the machine. It worked for me.

Please refer this [link ](https://stackoverflow.com/a/57511535/5352831)
